apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
  - host: grafana.10.65.213.19.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
